Templates
GurevichVarvara/GameMuster pull request #1
Opened 2021-03-29 08:02 UTC by GurevichVarvara

Main page is not ready yet. 

I have a problem with loading static that is why I've been coping styles into style-tag.

2021-03-29 15:33 UTC, GurevichVarvara commented
Main page is absolutely ready. 

I'm not sure if your monitor size is the same as mine that is why I attached screenshots.

![Main page](https://user-images.githubusercontent.com/34894826/112861050-1de99c80-90bd-11eb-9ebc-3cef250b75fd.png)
![Main page with the filter opened](https://user-images.githubusercontent.com/34894826/112861066-217d2380-90bd-11eb-905a-eb235b8af40d.png)

2021-03-30 06:42 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                            <label for="customRange3" class="form-label">Generes</label>
There is a typo.

2021-03-30 06:52 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                    <div id="carouselExampleCaptions" class="carousel slide gamescarousel" data-interval="false">
I think it's better not to use carousel here since there will be pagination logic later. Please, create just game cards with page buttons in the bottom for now.

2021-03-30 06:58 UTC, aleksey-kuchik commented on .gitignore
> +.venv/
As for `.gitignore` file there are already options for python development, such as this one: https://github.com/github/gitignore/blob/master/Python.gitignore
You can use it as a base and add everything you don't need in your project to be committed later as it goes.

2021-03-30 07:00 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/static/gameMuster/css/style.css
> +}
As requirements say, please, take a look at BEM methodology [here](https://ru.bem.info/methodology/quick-start/). Using this approach will result in better styling structure.

2021-03-30 07:15 UTC, aleksey-kuchik requested changes
You should not commit your sqlite db file since this may contain some sensitive data.

2021-03-31 10:32 UTC, merged