Users
GurevichVarvara/GameMuster pull request #14
Opened 2021-04-14 13:49 UTC by GurevichVarvara

Login, Logout and Signup pages are ready
Email confirmation is ready too
I have some problems with password reset, instead of showing custom pages which is located as proper in templates/registration folder with correct file names, Django shows me its default templates. Do you have any idea what's going wrong?

2021-04-15 16:13 UTC, GurevichVarvara commented
Everything connected to user is ready.

2021-04-16 10:47 UTC, aleksey-kuchik commented
Can you merge another PR to master and then master to this branch? This will make review of this PR a lot easier.

2021-04-19 09:33 UTC, aleksey-kuchik requested changes

2021-04-19 09:33 UTC, aleksey-kuchik commented on studentLabTask/users/templates/users/signup.html
> +  <button class="btn btn-success" type="submit">Sing Up</button>
```suggestion
  <button class="btn btn-success" type="submit">Sign Up</button>
```

2021-04-19 09:33 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +        logout(request)
You should not login user when the account is created to avoid this check.

2021-04-19 09:33 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +    user.is_active = False
This should be the default. And actually let's replace this field with `activate_time` field so that we have more information about the user. If `'activate_time` is `None` it means that user is not active.

2021-04-19 09:33 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +        user = None
```suggestion
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.filter(pk=uid).first()
```

2021-04-19 09:33 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +        return HttpResponse('Activation link is invalid!')
```suggestion
    if not (user and EmailConfirmationTokenGenerator().check_token(user, token)):
        return HttpResponse('Activation link is invalid!')
    user.is_active = True
    user.save()
    login(request, user)
    return redirect('index')
```

2021-04-20 14:28 UTC, GurevichVarvara commented on studentLabTask/users/views.py
> +        logout(request)
I use this check for those users, who edit their emails from the edit page.
I think that it's quit logical because we perform initial email check when user creates his profile, so why should not we do this after creation?

2021-04-21 09:31 UTC, aleksey-kuchik requested changes
Can you also create make one migration instead of three? This would result in less code.

2021-04-21 09:31 UTC, aleksey-kuchik commented on studentLabTask/users/forms.py
> +                  'email')
I think user should be able to change the also birthday, first and last names.

2021-04-21 09:31 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +    return render(request, 'users/message.html',
Seems like the message `Please confirm your email address to complete the registration` would be sent if user is already registered and just edits the email.

2021-04-21 09:31 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +    user.active_time = datetime.now()
Please, check this article about the timezones: https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/

2021-04-21 09:36 UTC, aleksey-kuchik commented on studentLabTask/users/views.py
> +        logout(request)
I think this results in bad user experience. Imagine that you have been using the site for couple of years and you would like to change the email. When you do this, you're logged out of site and if you have made a mistake in the new email, you won't be able to login until admin changes your email in database.
Probably a better way to do it is to create a new field, smth like `unconfirmed_email` and save it when user edits it. When user confirms the email, we set the new email value and clean the unconfirmed email.

2021-04-28 08:19 UTC, aleksey-kuchik approved these changes
Great job!

2021-04-28 09:57 UTC, merged