Templates
GurevichVarvara/GameMuster pull request #2
Opened 2021-03-31 11:18 UTC by GurevichVarvara

2021-03-31 17:36 UTC, GurevichVarvara commented
All templates are ready.

2021-04-01 09:42 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/detail.html
> +{% extends 'gameMuster/nav.html' %}
I think this can be named something like `base.html`. This will make things more clear.

2021-04-01 09:45 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/static/gameMuster/css/style.css
> +/* Detail page title style */
This file should be split into multiple files to avoid such comments an be smaller. Imagine that you have a hundred pages in your application. Current approach would result in huge and uneditable `style.css` file.

2021-04-01 09:48 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                            <label for="customRange3" class="form-label">Platform</label>
Do you need `for` here?

2021-04-01 09:48 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                            <label for="customRange3" class="form-label">Genres</label>
Same as above.

2021-04-01 09:49 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                  <input class="form-check-input" type="checkbox" name="inlineRadioOptions" id="gener1" value="platformer">
Typo `gener1`. Also, try to avoid abbreviations in names.

2021-04-01 09:56 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                                <p class="card-text">{{ game.genres }}</p>
I think this needs some better styling than just python list rendering.

2021-04-01 09:57 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/temp_models.py
> +        game = Game('PACKMAN',
It's "Pacman", not "Packman"!

2021-04-01 10:00 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                  <input class="form-check-input" type="checkbox" name="inlineRadioOptions" id="gener2" value="arcade" disabled>
Te same as above.

2021-04-01 10:06 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                    </div>
I think this can be moved to a separate template as it can be potentially reused.

2021-04-01 10:09 UTC, aleksey-kuchik commented on studentLabTask/studentLabTask/settings.py
> +
Blank new lines.

2021-04-01 10:10 UTC, aleksey-kuchik commented on test.diff
> ++.idea
This file should not be in the repo.

2021-04-01 10:10 UTC, aleksey-kuchik requested changes
Added some comments.

2021-04-02 10:02 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/base.html
> +    <link rel="stylesheet" type="text/css" href="{% static 'gameMuster/css/detail.css' %}">
Do you need al these styles on each page? I guess you need `detail.css` only on detail page and `index.css` only on index page.

2021-04-02 10:04 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                {% endfor %}
I think you don't need disabled genres. What logic do you want to implement with this?

2021-04-02 10:06 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                    <img src={{ game.img_url }} class="card-img-top" alt="game icon">
I think you can use BEM naming here, smth like `card__image`

2021-04-02 10:07 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                {% endfor %}
I think you don't need disabled platforms. What logic do you want to implement with this?

2021-04-02 10:08 UTC, aleksey-kuchik reviewed
Added some comments.

2021-04-03 09:15 UTC, aleksey-kuchik approved these changes
Looking good

2021-04-05 10:49 UTC, merged