Twitter igdb wrappers
GurevichVarvara/GameMuster pull request #3
Opened 2021-04-05 15:35 UTC by GurevichVarvara

Filter panel does not work for now, the same about tweets. 
Working with igdb api is finished.

2021-04-06 15:14 UTC, GurevichVarvara commented
Everything connecting API's is done I think.

2021-04-08 11:36 UTC, aleksey-kuchik requested changes
Good job, left some comments.

2021-04-08 11:36 UTC, aleksey-kuchik commented on .gitignore
> +
Blank line.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +    def request(self, endpoint, params=None):
This should be made protected and renamed to `_post` since this doesn't allow to use any other methods.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +                  **additional_params}
```suggestion
        params = {'fields': 'id, name, cover.image_id, genres.name,'
                            'summary, release_dates,'
                            'aggregated_rating,'
                            'aggregated_rating_count,'
                            'rating, rating_count,'
                            'screenshots.image_id,'
                            'platforms.name',
                     'filter[cover][not_eq]': 'null',
                     'filter[genres][not_eq]': 'null',
                     'filter[screenshots][not_eq]': 'null',
                    **additional_params}
```

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +                game['release_dates'] = 'no release date'
This should be handled by a template, since it is responsible to display logic.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +            game['rating'] = round(game.get('rating', 0), 1)
Rounding can be done in template as well. What if you need to analyze the data returned from the API more precisely later?

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +            game['aggregated_rating_count'] = game.get('aggregated_rating_count', 0)
Better use `None` in this cases since ratings are not 0, they are not specified.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/twitter_wrapper.py
> +    def request(self, params=None):
Should be made protected and renamed as in the case with igdb wrapper.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/games_manager.py
> +TWITTER_BEARER_TOKEN = os.environ.get('TWITTER_BEARER_TOKEN')
This should be moved to settings module.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/games_manager.py
> +        game = self.igdb_wrapper.get_games({'filter[id][eq]': game_id})[0]
Game manager should know nothing about how igdb api is structured, this logic should be in igdb api wrapper. That's why you should just pass a parameter `ids` here and reimplement the wrapper method. Also what happens if the game is not found?

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/temp_models.py
> +        self.genres_str = ' '.join(genres)
Why not to use list here and handle the formatting in template?

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/detail.html
> +                {% endif %}
Comparing to a magic constant. This should be a `None` comparison.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                        {% endif %}
Code duplication, you need just to set checked here or not, other attributes are exactly the same.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/templates/gameMuster/index.html
> +                                        {% endif %}
The same as above.

2021-04-08 11:36 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/views.py
> +    params_from_filter['filter[' + option + '][eq]'] = '(' + ','.join(chosen_params) + ')'
The view should know nothing about how igdb api structure. You should just pass genres and platforms as keyword arguments to a wrapper method if needed.

2021-04-12 10:10 UTC, aleksey-kuchik requested changes

2021-04-12 10:10 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/views.py
> +        chosen_params_container[option].append(int(param))
Try to use [pure functions](https://en.wikipedia.org/wiki/Pure_function) in your code when it's possible.

2021-04-12 10:10 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/views.py
> +        #game_manager = MockedGameManager()
Commented code.

2021-04-12 10:10 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/views.py
> +                                                    rating=chosen_params['rating'])
What happens if not games are found? Lookup error and 500?

2021-04-15 08:47 UTC, aleksey-kuchik commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +            raise Http404
But technically it can be a different error, right? Why is 404 returned every time?

2021-04-15 10:55 UTC, GurevichVarvara commented on studentLabTask/gameMuster/api_wrappers/igdb_wrapper.py
> +            raise Http404
Actually I think that 500 error could be suitable here too, but 404  is more, don't you think? 
Or you mean another status code?

2021-04-16 10:46 UTC, aleksey-kuchik approved these changes

2021-04-16 10:59 UTC, merged