Favorite games
GurevichVarvara/GameMuster pull request #30
Opened 2021-04-22 14:45 UTC by GurevichVarvara

Created favorite game model with soft deletion and page for them.
Also fixed pagination logic, there were some troubles with different urls. 
Searchbar doesn't work yet cause I think it would be better to implement its logic when the game model'd be added (just using icontains). 
Heroku deployment is not finished.

2021-04-26 15:51 UTC, GurevichVarvara commented
Everything is ready.

2021-04-28 08:20 UTC, aleksey-kuchik commented
Can you merge this https://github.com/GurevichVarvara/GameMuster/pull/14#pullrequestreview-646733030 to master and then merge master into this branch to make it easier for review?

2021-04-29 06:04 UTC, aleksey-kuchik requested changes
You can decide which game manager to use during first import of `gameMuster.games_manager` module with that code in it:
```python3
games_manager = MockedGamesManager() if settings.DEV_DATA_MODE else GamesManager()
```
And then to use it just import it:
```python3
from gameMuster.games_manager import games_manager
games_manager.do_some_stuff()
```

2021-04-29 10:43 UTC, GurevichVarvara commented on gameMuster/views.py
> +               in FavoriteGame.objects.filter(user=request.user))
There are no duplicates, that was made for passing set to a template for efficient check if the game id in the favorite games

2021-04-29 10:45 UTC, GurevichVarvara commented on gameMuster/views.py
> +    pass
I have MockedGamesManager in different dir form GamesManager and this folder isn't tracked by git, so if there are no module to work with mocked data MockedGamesManager would not be imported

2021-04-29 10:47 UTC, GurevichVarvara commented on gameMuster/games_manager.py
> +        return cls.instance
I use it in a lot of methods in games view. Is it better to create new instance of GamesManager every time one of those methods is called?

2021-04-29 10:59 UTC, GurevichVarvara commented on gameMuster/views.py
> +    pass
But actually I don't like that solution and I'd remove that entire module, so that if the DEV_DATA_MODE was True I'd just use mocked response from igdb api instead of request data

2021-04-30 12:22 UTC, aleksey-kuchik commented on gameMuster/games_manager.py
> +        return cls.instance
Creating new instances is not a big problem since those don't store any huge amounts of data and complex calculations. I've left a suggestion for better approach in a root comment to this PR.

2021-04-30 12:26 UTC, aleksey-kuchik commented on gameMuster/views.py
> +    pass
I think you should rather include this module to git tracked files since on a real project other devs may also find it useful.

2021-04-30 12:35 UTC, aleksey-kuchik commented on gameMuster/views.py
> +               in FavoriteGame.objects.filter(user=request.user))
`in` operator works with lists just fine and I don't think this optimization saves much. But it complicates the code and sacrifices readability. Not too much, but still.

2021-05-03 10:06 UTC, aleksey-kuchik commented on gameMuster/mocked_data/mocked_games_manager.py
> +        return len(set(filter_names) & set(game_params)) > 0
```suggestion
        filter_names = [x['name'] for x in filter_map if x['id'] in filter_ids]
        return any(f in game_params for f in filter_names)
```

2021-05-03 10:13 UTC, aleksey-kuchik requested changes

2021-05-03 10:13 UTC, aleksey-kuchik commented on gameMuster/models.py
> +        print('fal')
Debugging code?

2021-05-04 09:46 UTC, aleksey-kuchik approved these changes

2021-05-04 11:11 UTC, merged