Games refresh
GurevichVarvara/GameMuster pull request #45
Opened 2021-05-04 11:13 UTC by GurevichVarvara

2021-05-06 16:00 UTC, GurevichVarvara commented
To make celery task periodic I've defined a PeriodicTask object.

2021-05-07 11:04 UTC, aleksey-kuchik requested changes

2021-05-07 11:04 UTC, aleksey-kuchik commented on gameMuster/views.py
> +                         .filter(user_rating__gte=chosen_params['rating'])))
Also you can use variables per filter instead of dict object `chosen_params`
```suggestion
    game_list = Game.objects
    if chosen_params['platforms']:
         game_list = game_list.filter(platforms__pk__in=chosen_params['platforms'])
    if chosen_params['genres']:
         game_list = game_list.filter(genres__pk__in=chosen_params['genres'])
    if chosen_params['rating']:
         game_list = game_list.filter(user_rating__gte=chosen_params['rating'])
    game_list = game_list.all()
```

2021-05-13 11:30 UTC, aleksey-kuchik requested changes

2021-05-17 08:55 UTC, aleksey-kuchik approved these changes

2021-05-17 09:13 UTC, merged