Unit tests
GurevichVarvara/GameMuster pull request #84
Opened 2021-06-04 18:57 UTC by GurevichVarvara

2021-06-08 12:46 UTC, GurevichVarvara commented on gameMuster/tests/test_views.py
> +            [self.game.id]
If I compared lists of Game objects, I'd get such error: '<Game object>' != <Game object>
That's why I decided to compare lists of ids.

2021-06-08 13:17 UTC, GurevichVarvara commented on gameMuster/tests/test_views.py
> +            [self.game.id]
I solved it. List comparison works correct with assertCountEqual, but not with assertQuerysetEqual.

2021-06-08 15:06 UTC, aleksey-kuchik requested changes

2021-06-08 15:06 UTC, aleksey-kuchik commented on gameMuster/tests/test_views.py
> +        )
You should check not the count but rather games here since count may be the same with other games, right?

2021-06-24 14:08 UTC, GurevichVarvara commented
I added model factories and removed protected method tests

2021-06-25 12:57 UTC, GurevichVarvara commented on gameMuster/tests/test_views.py
> +        )
assertCountEqual (Python 3) is the analogue of the ListItemsEqual (Python 2).

2021-08-19 09:39 UTC, merged